# Generated by Django 3.1.2 on 2020-11-03 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=70)),
                ('cantidad_producto', models.PositiveIntegerField()),
                ('descripcion_producto', models.CharField(max_length=300)),
                ('precio_unit', models.FloatField(max_length=20)),
            ],
        ),
    ]
