# Generated by Django 3.1.3 on 2020-11-06 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id_ciudad', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('nombre_ciudad', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Comprador',
            fields=[
                ('cedula_comprador', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=70)),
                ('apellido', models.CharField(max_length=70)),
                ('correo_electronico', models.EmailField(max_length=70)),
                ('direccion', models.CharField(max_length=70)),
                ('telefono', models.IntegerField()),
                ('fecha_nacimiento', models.DateField()),
                ('id_ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enroll.ciudad')),
            ],
        ),
        migrations.CreateModel(
            name='Mensajero',
            fields=[
                ('cedula_mensajero', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=70)),
                ('apellido', models.CharField(max_length=70)),
                ('correo_electronico', models.EmailField(max_length=70)),
                ('direccion', models.CharField(max_length=70)),
                ('telefono', models.IntegerField()),
                ('fecha_nacimiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('cedula_propietario', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=70)),
                ('apellido', models.CharField(max_length=70)),
                ('correo_electronico', models.EmailField(max_length=70)),
                ('direccion', models.CharField(max_length=70)),
                ('telefono', models.IntegerField()),
                ('fecha_nacimiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Salario_Trabajador',
            fields=[
                ('id_salario', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('sueldo_base', models.FloatField()),
                ('honorarios', models.FloatField()),
                ('seguro_social', models.FloatField()),
                ('pensiones', models.FloatField()),
                ('sueldo_total', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Producto',
            fields=[
                ('id_tipo', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('nombre_tipo', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Trabajador',
            fields=[
                ('id_tipo', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('tipo_trabajador', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('cedula_trabajador', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=70)),
                ('apellido', models.CharField(max_length=70)),
                ('correo_electronico', models.EmailField(max_length=70)),
                ('direccion', models.CharField(max_length=70)),
                ('telefono', models.IntegerField()),
                ('fecha_nacimiento', models.DateField()),
                ('id_tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enroll.tipo_trabajador')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('nombre_proveedor', models.CharField(max_length=70)),
                ('direccion', models.CharField(max_length=70)),
                ('telefono', models.IntegerField()),
                ('correo_electronico', models.EmailField(max_length=70)),
                ('cedula_propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enroll.propietario')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=70)),
                ('cantidad_producto', models.PositiveIntegerField()),
                ('descripcion_producto', models.CharField(max_length=300)),
                ('precio_unit', models.FloatField()),
                ('id_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enroll.proveedor')),
                ('id_tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enroll.tipo_producto')),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id_factura', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('subtotal', models.FloatField()),
                ('iva', models.FloatField()),
                ('total', models.FloatField()),
                ('cedula_comprador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enroll.comprador')),
                ('cedula_mensajero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enroll.mensajero')),
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enroll.product')),
            ],
        ),
        migrations.CreateModel(
            name='Especificacion_Factura',
            fields=[
                ('id_especificacion', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('cantidad_compra', models.IntegerField()),
                ('importe', models.FloatField()),
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enroll.product')),
                ('id_factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enroll.factura')),
            ],
        ),
    ]
