# Generated by Django 3.1.3 on 2020-11-05 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0003_auto_20201105_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='precio_unit',
            field=models.FloatField(),
        ),
    ]
